/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.portal.rh.employee.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeProject service. Represents a row in the &quot;RH_EmployeeProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.portal.rh.employee.model.impl.EmployeeProjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.portal.rh.employee.model.impl.EmployeeProjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeProject
 * @generated
 */
@ProviderType
public interface EmployeeProjectModel
	extends BaseModel<EmployeeProject>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee project model instance should use the {@link EmployeeProject} interface instead.
	 */

	/**
	 * Returns the primary key of this employee project.
	 *
	 * @return the primary key of this employee project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee project.
	 *
	 * @param primaryKey the primary key of this employee project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee project ID of this employee project.
	 *
	 * @return the employee project ID of this employee project
	 */
	public long getEmployeeProjectId();

	/**
	 * Sets the employee project ID of this employee project.
	 *
	 * @param employeeProjectId the employee project ID of this employee project
	 */
	public void setEmployeeProjectId(long employeeProjectId);

	/**
	 * Returns the employee ID of this employee project.
	 *
	 * @return the employee ID of this employee project
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee project.
	 *
	 * @param employeeId the employee ID of this employee project
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the project ID of this employee project.
	 *
	 * @return the project ID of this employee project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this employee project.
	 *
	 * @param projectId the project ID of this employee project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the allocated hours of this employee project.
	 *
	 * @return the allocated hours of this employee project
	 */
	public int getAllocatedHours();

	/**
	 * Sets the allocated hours of this employee project.
	 *
	 * @param allocatedHours the allocated hours of this employee project
	 */
	public void setAllocatedHours(int allocatedHours);

	/**
	 * Returns the group ID of this employee project.
	 *
	 * @return the group ID of this employee project
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee project.
	 *
	 * @param groupId the group ID of this employee project
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee project.
	 *
	 * @return the company ID of this employee project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee project.
	 *
	 * @param companyId the company ID of this employee project
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public EmployeeProject cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}