/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.portal.rh.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Project service. Represents a row in the &quot;RH_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.portal.rh.employee.model.impl.ProjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.portal.rh.employee.model.impl.ProjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Project
 * @generated
 */
@ProviderType
public interface ProjectModel
	extends BaseModel<Project>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the name of this project.
	 *
	 * @return the name of this project
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this project.
	 *
	 * @param name the name of this project
	 */
	public void setName(String name);

	/**
	 * Returns the description of this project.
	 *
	 * @return the description of this project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project.
	 *
	 * @param description the description of this project
	 */
	public void setDescription(String description);

	/**
	 * Returns the start date of this project.
	 *
	 * @return the start date of this project
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this project.
	 *
	 * @param startDate the start date of this project
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this project.
	 *
	 * @return the end date of this project
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this project.
	 *
	 * @param endDate the end date of this project
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the active of this project.
	 *
	 * @return the active of this project
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this project is active.
	 *
	 * @return <code>true</code> if this project is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this project is active.
	 *
	 * @param active the active of this project
	 */
	public void setActive(boolean active);

	/**
	 * Returns the group ID of this project.
	 *
	 * @return the group ID of this project
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project.
	 *
	 * @param groupId the group ID of this project
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project.
	 *
	 * @return the user ID of this project
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project.
	 *
	 * @param userId the user ID of this project
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project.
	 *
	 * @return the user uuid of this project
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project.
	 *
	 * @param userUuid the user uuid of this project
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project.
	 *
	 * @return the user name of this project
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project.
	 *
	 * @param userName the user name of this project
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Project cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}